# syntax=docker/dockerfile:1

# Assumes that dist/*.whl has been built

FROM thehale/python-poetry:2.1.3-py3.11-slim as python-base

RUN apt-get update -y
RUN apt-get install gcc -y

COPY ./dist/*.whl ./

RUN pip install *.whl

CMD ["ouroboros-docker-server"]